
@url = http://localhost
# @name login
POST {{url}}/api
Authorization: Basic delight:delight

{
    "devicetype": "tester"
}

###
@token = {{login.response.body.0.success.username}}
#
GET {{url}}/api/{{token}}/config

###

GET {{url}}/api/{{token}}/lights

###

GET {{url}}/api/{{token}}/lights/a4:c1:38:ae:c6:5e:e1:02-01

###

GET {{url}}/api/{{token}}/sensors
